### ISSUE TITLE
Server Start issue in Master

### ISSUE THREAD

**Issue by prajneya** [prajneya/SocialIIIT#35]
Receiving the following error on starting the server in master branch.

![Screenshot from 2020-11-02 18-37-32](https://user-images.githubusercontent.com/15520626/97871524-a5afc280-1d3a-11eb-9f44-617106c81f6c.png)

Logs say that the error popped up after @Debayan-Saha 's commits.

![Screenshot from 2020-11-02 18-40-26](https://user-images.githubusercontent.com/15520626/97871800-fa533d80-1d3a-11eb-9dec-c742986569b1.png)

@SRDewan @Debayan-Saha Please look into this ASAP/suggest a fix. Master code cannot remain broken.

**Comment by Debayan-Saha** [comment]
i am looking into it

**Comment by SRDewan** [comment]
Fixed.
