### ISSUE TITLE
Change Trending Tag Algorithm

### ISSUE THREAD

**Issue by prajneya** [prajneya/SocialIIIT#83]
Problems:
1. Trending Tag iterates through all posts to know number of tags used which is O(n), n being the number of posts.
2. Creates its own array of tags

Solution:
Create a new collection called tags and while creating posts and assigning tags, increment the value of tags in the aforesaid collection.  This solves both the above problems, reducing the complexity, and maintaining tags in a separate place.

**Comment by Dayitva** [comment]
Issue Resolved
